'use strict'

// ============================================================
// emit/emit-cue.js  --  write a standard .cue sheet (tracklist)
// ============================================================

const fs = require('fs')
const path = require('path')
const { fmtCueIndex } = require('../lib/util')

function q(s) {
  return '"' + String(s == null ? '' : s).replace(/"/g, "'") + '"'
}

// timeline -> .cue string. `audioFile` is what the FILE line references.
function toCue(timeline, audioFile) {
  const file = audioFile ? path.basename(audioFile) : path.basename(timeline.mix || 'mix.wav')
  const ext = path.extname(file).toLowerCase()
  const fmt = ext === '.mp3' ? 'MP3' : ext === '.wav' ? 'WAVE' : 'WAVE'

  // Cue sheets are linear: one INDEX per track, sorted, no overlaps.
  const segs = [...timeline.segments].sort((a, b) => a.start_s - b.start_s)

  const L = []
  L.push('REM Generated by dj-id')
  if (timeline.engine) L.push('REM ENGINE ' + timeline.engine)
  L.push('TITLE ' + q('DJ mix'))
  L.push('FILE ' + q(file) + ' ' + fmt)
  segs.forEach((s, i) => {
    const n = String(i + 1).padStart(2, '0')
    L.push('  TRACK ' + n + ' AUDIO')
    L.push('    TITLE ' + q(s.title || s.display))
    L.push('    PERFORMER ' + q(s.artist || 'Unknown'))
    if (s.bpm) L.push('    REM BPM ' + s.bpm)
    if (s.key) L.push('    REM KEY ' + s.key)
    if (s.pitch_pct) L.push('    REM PITCH ' + (s.pitch_pct > 0 ? '+' : '') + s.pitch_pct + '%')
    L.push('    REM CONFIDENCE ' + s.confidence)
    L.push('    INDEX 01 ' + fmtCueIndex(s.start_s))
  })
  return L.join('\n') + '\n'
}

function emitCue(timeline, outPath, audioFile) {
  fs.writeFileSync(outPath, toCue(timeline, audioFile))
  return outPath
}

module.exports = { emitCue, toCue }
